[package]
name = "captcha-image"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
image = "0.23.14"
rusttype = "0.9.2"
base64 = "0.13.0"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]